### ISSUE TITLE
doubts in relation to embedding

### ISSUE THREAD

**Issue by TianqiLiu1** [justarter/E2URec#1]
Thanks for your contribution. I notice that you mention the embedding file in your code. But I can find neither the code nor the data after embedding. Can you provide some information about that? Thanks very much.

**Comment by justarter** [comment]
Hi, what "embedding" are you referring to? Do you mean the T5 checkpoint?

**Comment by TianqiLiu1** [comment]
in /[data_preprocess](https://github.com/justarter/E2URec/tree/main/data_preprocess)
/load_prompt_ml1m.py 
line 143 indice_dir="./embeddings",

**Comment by justarter** [comment]
"zero_shot_ret_get_prompt" function in load_prompt_ml1m.py will not be used. Just ignore it

**Comment by TianqiLiu1** [comment]
Ok, thanks for your timely reply !
